name: blinkode
favicon: null
layout_spectrum: 1
typography_spectrum: 0.56325
title: Grid of Things
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c10101'
    - '#010101'
    - '#807f81'
    - '#c0bdbd'
    - '#effcff'
  brandStrength: 0.10747646214440465
  lightness: 0.8980549378320575
  saturation: 0.9289788561873138
  rhythmicContrast: 0.32534823939204216
purpose: []
