name: blinkode
favicon: null
layout_spectrum: 0.8067882384639233
typography_spectrum: 0.5080155704636127
title: Grid of Things
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.10747646214440465
  lightness: 0.8980549378320575
  saturation: 0.9289788561873138
  rhythmicContrast: 0.32534823939204216
purpose: []
